### ISSUE TITLE
Is there any other way to show online users

### ISSUE THREAD

**Issue by Sananthu-47** [Sananthu-47/Social_Feeds#3]
As i have used setinterval in profile.php to obtain the online users status with AJAX but still i feel there will be better way to obtain the data from database.

Setinterval calls retrieves the data every specified period this may overload the server .

**Comment by ChaaruManjuraj** [comment]
Well, I assume you meant that you've tried to ping the server asynchronously to read data from the server and writing to the same. This is actually standard practice that most of the forums, communities, and social networks use. Since you feel it might overload your server, I'm suggesting you a new way to achieve it with Reactjs.

You can set up your server file which sends data with Websockets. Make the counter observable and then subscribe to its changes in your react component. Every time counter changes, use setState to trigger a view update. Contact me for more information.

**Comment by Sananthu-47** [comment]
Thank you
